/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser; // Untuk Impor/Ekspor
import java.io.File; // Untuk Impor/Ekspor
import java.io.FileWriter; // Untuk Ekspor
import java.io.BufferedReader; // Untuk Impor
import java.io.FileReader; // Untuk Impor
import java.io.IOException; // Untuk IO
import Database.Koneksi;

//untuk import export pdf
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;




public class BukuAlamatFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BukuAlamatFrame.class.getName());
    private final Connection koneksi;
    private int selectedId = -1;
    private boolean isDataModified = false;
    
    public BukuAlamatFrame() {
        initComponents();
        koneksi = Koneksi.getKoneksi(); // Mendapatkan koneksi
        loadData();
        
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { setDataModified(true); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { setDataModified(true); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { setDataModified(true); }
        };
        txtNama.getDocument().addDocumentListener(docListener);
        txtTelp.getDocument().addDocumentListener(docListener);
        txtEmail.getDocument().addDocumentListener(docListener);
        txtAlamat.getDocument().addDocumentListener(docListener);
        txtKeterangan.getDocument().addDocumentListener(docListener);
        cmbProperti.addActionListener(e -> {
            setDataModified(true);
        });
        // --------------------------------------------------------
        
        // Atur status awal sebagai tidak termodifikasi
        setDataModified(false); 
        
        // Panggil penanganan close window
        setupWindowCloseConfirmation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbProperti = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI BUKU ALAMAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBuku);

        jLabel2.setText("Nama                     :");

        jLabel3.setText("Alamat Lengkap   :");

        jLabel4.setText("Keterangan           : ");

        jLabel5.setText("Telepon                 :");

        jLabel6.setText("Email                     :");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane4.setViewportView(txtKeterangan);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel7.setText("Properti                 :");

        cmbProperti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rumah", "Kantor", "Sekolah", "Gedung Industri", "Apartemen", "Hotel", "Toko", "Pusat Pembelajaan", "Universitas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNama)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(txtEmail)
                                    .addComponent(jScrollPane4)
                                    .addComponent(cmbProperti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave)))
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbProperti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEkspor.setText("EKSPOR");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        btnImpor.setText("IMPOR");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        confirmExit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImporActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File untuk Impor");
        
        // --- BUAT FILTER BARU ---
        javax.swing.filechooser.FileNameExtensionFilter txtFilter = 
                new javax.swing.filechooser.FileNameExtensionFilter("Text Files (*.txt)", "txt");
        javax.swing.filechooser.FileNameExtensionFilter pdfFilter = 
                new javax.swing.filechooser.FileNameExtensionFilter("PDF Files (*.pdf)", "pdf");
        
        fileChooser.addChoosableFileFilter(txtFilter);
        fileChooser.addChoosableFileFilter(pdfFilter);
        fileChooser.setFileFilter(txtFilter); // Default ke TXT
        
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            
            javax.swing.filechooser.FileNameExtensionFilter currentFilter = 
                    (javax.swing.filechooser.FileNameExtensionFilter) fileChooser.getFileFilter();

            // --- PANGGIL METODE SESUAI FILTER ---
            if (currentFilter.getDescription().equals("Text Files (*.txt)")) {
                importDataFromTXT(fileToOpen);
            } else if (currentFilter.getDescription().equals("PDF Files (*.pdf)")) {
                importDataFromPDF(fileToOpen);
            }
        }
    }//GEN-LAST:event_btnImporActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Kontak");
        
        // --- BUAT FILTER BARU ---
        javax.swing.filechooser.FileNameExtensionFilter txtFilter = 
                new javax.swing.filechooser.FileNameExtensionFilter("Text Files (*.txt)", "txt");
        javax.swing.filechooser.FileNameExtensionFilter pdfFilter = 
                new javax.swing.filechooser.FileNameExtensionFilter("PDF Files (*.pdf)", "pdf");
        
        fileChooser.addChoosableFileFilter(txtFilter);
        fileChooser.addChoosableFileFilter(pdfFilter);
        
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String path = fileToSave.getAbsolutePath();
            
            javax.swing.filechooser.FileNameExtensionFilter currentFilter = 
                    (javax.swing.filechooser.FileNameExtensionFilter) fileChooser.getFileFilter();

            // --- PANGGIL METODE SESUAI FILTER ---
            if (currentFilter.getDescription().equals("Text Files (*.txt)")) {
                if (!path.toLowerCase().endsWith(".txt")) {
                    fileToSave = new File(path + ".txt");
                }
                exportDataToTXT(fileToSave);
            } else if (currentFilter.getDescription().equals("PDF Files (*.pdf)")) {
                 if (!path.toLowerCase().endsWith(".pdf")) {
                    fileToSave = new File(path + ".pdf");
                }
                exportDataToPDF(fileToSave);
            }
            // Tambahkan logika untuk format lain (CSV/JSON) jika diperlukan
        }
    }//GEN-LAST:event_btnEksporActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
                                     
        int baris = tblBuku.getSelectedRow();
        if (baris == -1) return; 

        // Ambil ID dari kolom pertama (index 0)
        selectedId = (int) tblBuku.getValueAt(baris, 0);

        // Ambil data lengkap dari database berdasarkan ID
        String sql = "SELECT * FROM kontak WHERE id = ?";
        try (PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            pstmt.setInt(1, selectedId);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    txtNama.setText(rs.getString("nama"));
                    txtTelp.setText(rs.getString("telepon"));
                    txtEmail.setText(rs.getString("email"));
                    txtAlamat.setText(rs.getString("alamat"));
                    txtKeterangan.setText(rs.getString("keterangan"));
                    cmbProperti.setSelectedItem(rs.getString("properti"));
                    
                    // Aktifkan tombol Update dan Delete
                    btnSave.setEnabled(false);
                    btnUpdate.setEnabled(true);
                    btnDelete.setEnabled(true);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil detail data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BukuAlamatFrame().setVisible(true));
    }
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Telepon");
        model.addColumn("Email");
        model.addColumn("Properti");
        model.addColumn("Keterangan");
        
        // Mengubah nama kolom default NetBeans (Title 1, Title 2, ...)
        tblBuku.setModel(model);

        String sql = "SELECT id, nama, telepon, email, properti, keterangan FROM kontak";
        
        try (Statement stmt = koneksi.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nama"),
                    rs.getString("telepon"),
                    rs.getString("email"),
                    rs.getString("properti"),
                    rs.getString("keterangan") // <-- AMBIL DATA KETERANGAN
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 2. CREATE: Menyimpan data baru
    private void saveData() {
        String nama = txtNama.getText();
        String telepon = txtTelp.getText();
        String email = txtEmail.getText();
        String alamat = txtAlamat.getText();
        String properti = cmbProperti.getSelectedItem().toString();
        String keterangan = txtKeterangan.getText();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!telepon.isEmpty() && !isNumeric(telepon)) {
            JOptionPane.showMessageDialog(this, "Nomor Telepon hanya boleh berisi angka.", "Validasi", JOptionPane.WARNING_MESSAGE);
            txtTelp.requestFocus(); // Fokuskan kursor ke field Telepon
            return;
        }
        
        // --- VALIDASI EMAIL ---
        if (!email.isEmpty() && !isValidEmail(email)) {
             JOptionPane.showMessageDialog(this, "Format Email tidak valid (harus mengandung '@').", "Validasi", JOptionPane.WARNING_MESSAGE);
             txtEmail.requestFocus(); // Fokuskan kursor ke field Email
             return;
        }

        String sql = "INSERT INTO kontak (nama, telepon, email, alamat, properti, keterangan) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            pstmt.setString(1, nama);
            pstmt.setString(2, telepon);
            pstmt.setString(3, email);
            pstmt.setString(4, alamat);
            pstmt.setString(5, properti);
            pstmt.setString(6, keterangan);
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            clearFields();
            loadData();
            setDataModified(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 3. UPDATE: Mengubah data yang sudah ada
    private void updateData() {
        if (selectedId == -1) return; 

        String nama = txtNama.getText();
        String telepon = txtTelp.getText();
        String email = txtEmail.getText();
        String alamat = txtAlamat.getText();
        String properti = cmbProperti.getSelectedItem().toString();
        String keterangan = txtKeterangan.getText();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!telepon.isEmpty() && !isNumeric(telepon)) {
            JOptionPane.showMessageDialog(this, "Nomor Telepon hanya boleh berisi angka.", "Validasi", JOptionPane.WARNING_MESSAGE);
            txtTelp.requestFocus();
            return;
        }
        
        // --- VALIDASI EMAIL ---
        if (!email.isEmpty() && !isValidEmail(email)) {
             JOptionPane.showMessageDialog(this, "Format Email tidak valid (harus mengandung '@').", "Validasi", JOptionPane.WARNING_MESSAGE);
             txtEmail.requestFocus();
             return;
        }
        
        String sql = "UPDATE kontak SET nama = ?, telepon = ?, email = ?, alamat = ?, properti = ?, keterangan = ? WHERE id = ?";
        try (PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            pstmt.setString(1, nama);
            pstmt.setString(2, telepon);
            pstmt.setString(3, email);
            pstmt.setString(4, alamat);
            pstmt.setString(5, properti);
            pstmt.setString(6, keterangan);
            pstmt.setInt(7, selectedId);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            clearFields();
            loadData();
            setDataModified(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 4. DELETE: Menghapus data
    private void deleteData() {
        if (selectedId == -1) return;

        int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kontak ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM kontak WHERE id = ?";
            try (PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
                pstmt.setInt(1, selectedId);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                clearFields();
                loadData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    // Metode untuk membersihkan semua field input
    private void clearFields() {
        txtNama.setText("");
        txtTelp.setText("");
        txtEmail.setText("");
        txtAlamat.setText("");
        txtKeterangan.setText("");
        cmbProperti.setSelectedItem("Rumah");
        
        selectedId = -1;
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        tblBuku.clearSelection();
    }
    
    private void setDataModified(boolean modified) {
        isDataModified = modified;
    }
    
    private void exportData() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Kontak");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            // Pastikan ekstensi .csv
            if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }
            
            try (FileWriter fw = new FileWriter(fileToSave)) {
                // Header CSV
                fw.append("ID,Nama,Telepon,Email,Alamat,Properti,Keterangan\n");
                
                String sql = "SELECT id, nama, telepon, email, alamat, properti, keterangan FROM kontak";
                try (Statement stmt = koneksi.createStatement();
                     ResultSet rs = stmt.executeQuery(sql)) {

                    while (rs.next()) {
                        // Data (dibatasi oleh koma)
                        fw.append(rs.getInt("id") + ",");
                        fw.append(rs.getString("nama") + ",");
                        fw.append(rs.getString("telepon") + ",");
                        fw.append(rs.getString("email") + ",");
                        // Ganti baris baru atau koma dalam teks dengan spasi
                        fw.append(rs.getString("alamat").replaceAll("[\n,]", " ") + ","); 
                        fw.append(rs.getString("properti") + ",");
                        fw.append(rs.getString("keterangan").replaceAll("[\n,]", " ") + "\n");
                    }
                    JOptionPane.showMessageDialog(this, "Ekspor berhasil ke: " + fileToSave.getAbsolutePath());
                }
            } catch (SQLException | IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal ekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    // Implementasi Impor (Import) dari CSV (Sederhana)
    private void importData() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV untuk Impor");
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            int importedCount = 0;
            String sql = "INSERT INTO kontak (nama, telepon, email, alamat, properti, keterangan) VALUES (?, ?, ?, ?, ?, ?)";

            try (BufferedReader br = new BufferedReader(new FileReader(fileToOpen));
                 PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
                
                String line;
                boolean isHeader = true;
                while ((line = br.readLine()) != null) {
                    if (isHeader) {
                        isHeader = false; // Lewati baris header
                        continue;
                    }

                    // Pemisahan sederhana (mungkin bermasalah jika ada koma dalam data)
                    String[] data = line.split(",", -1); 
                    
                    // Asumsi urutan data: ID,Nama,Telepon,Email,Alamat,Properti,Keterangan
                    // ID (index 0) diabaikan karena auto-increment
                    if (data.length >= 7) {
                        pstmt.setString(1, data[1]); // Nama
                        pstmt.setString(2, data[2]); // Telepon
                        pstmt.setString(3, data[3]); // Email
                        pstmt.setString(4, data[4]); // Alamat
                        pstmt.setString(5, data[5]); // Properti
                        pstmt.setString(6, data[6]); // Keterangan
                        pstmt.addBatch(); // Tambahkan ke batch
                        importedCount++;
                    }
                }
                
                pstmt.executeBatch(); // Eksekusi semua INSERT
                JOptionPane.showMessageDialog(this, "Impor " + importedCount + " data berhasil!");
                loadData();
            } catch (IOException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal impor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private boolean isKontakExists(String nama, String telepon) throws SQLException {
        // Query: Hitung berapa baris yang punya Nama DAN Telepon ini
        String sql = "SELECT COUNT(*) FROM kontak WHERE nama = ? AND telepon = ?";
        try (PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            pstmt.setString(1, nama);
            pstmt.setString(2, telepon);
            
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    // Jika count > 0, data sudah ada
                    return rs.getInt(1) > 0; 
                }
            }
        }
        return false;
    }
    
    //Import export Data FIle txt
    private void exportDataToTXT(File fileToSave) {
        String sql = "SELECT nama, telepon, email, alamat, properti, keterangan FROM kontak";
        
        try (FileWriter fw = new FileWriter(fileToSave)) {
            // Header TXT (Menggunakan tab '\t' sebagai pemisah)
            fw.append("NAMA\tTELEPON\tEMAIL\tALAMAT\tPROPERTI\tKETERANGAN\n");

            try (Statement stmt = koneksi.createStatement();
                 ResultSet rs = stmt.executeQuery(sql)) {

                while (rs.next()) {
                    // Tulis data dengan pemisah tab
                    fw.append(rs.getString("nama") + "\t");
                    fw.append(rs.getString("telepon") + "\t");
                    fw.append(rs.getString("email") + "\t");
                    fw.append(rs.getString("alamat").replaceAll("[\n\t]", " ") + "\t"); 
                    fw.append(rs.getString("properti") + "\t");
                    fw.append(rs.getString("keterangan").replaceAll("[\n\t]", " ") + "\n");
                }
                JOptionPane.showMessageDialog(this, "Ekspor TXT berhasil ke: " + fileToSave.getAbsolutePath());
            }
        } catch (SQLException | IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal ekspor data ke TXT: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void importDataFromTXT(File fileToOpen) {
        String sql = "INSERT INTO kontak (nama, telepon, email, alamat, properti, keterangan) VALUES (?, ?, ?, ?, ?, ?)";
        int importedCount = 0;
        int duplicateCount = 0; // Tambahkan penghitung duplikat

        try (BufferedReader br = new BufferedReader(new FileReader(fileToOpen));
             java.sql.PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            
            // ... (Kode membaca header dan loop baris) ...
            String line;
            boolean isHeader = true;
            
            while ((line = br.readLine()) != null) {
                if (isHeader) {
                    isHeader = false; 
                    continue;
                }

                String[] data = line.split("\t", -1);
                
                if (data.length >= 6) { 
                    String nama = data[0].trim();
                    String telepon = data[1].trim();

                    // --- LOGIKA PENCEGAHAN DUPLIKASI ---
                    if (isKontakExists(nama, telepon)) {
                        duplicateCount++;
                        // Lewati baris ini dan lanjutkan ke baris berikutnya
                        continue; 
                    }
                    // ------------------------------------
                    
                    // Jika data unik, tambahkan ke batch INSERT
                    pstmt.setString(1, nama); 
                    pstmt.setString(2, telepon); 
                    pstmt.setString(3, data[2].trim()); // Email
                    pstmt.setString(4, data[3].trim()); // Alamat
                    pstmt.setString(5, data[4].trim()); // Properti
                    pstmt.setString(6, data[5].trim()); // Keterangan
                    pstmt.addBatch();
                    importedCount++;
                }
            }
            
            pstmt.executeBatch();
            
            // Berikan laporan lengkap
            String message = "Impor berhasil: " + importedCount + " data baru dimasukkan. ";
            if (duplicateCount > 0) {
                 message += duplicateCount + " data diduplikasi dan dilewati.";
            }
            JOptionPane.showMessageDialog(this, message);
            loadData();
        } catch (IOException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal impor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Impor ekspor Data File PDF
    private void exportDataToPDF(File fileToSave) {
        Document document = new Document(PageSize.A4.rotate()); // Menggunakan A4 landscape
        String sql = "SELECT id, nama, telepon, email, properti, keterangan FROM kontak";

        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
            document.open();

            // 1. Judul Dokumen
            document.add(new Paragraph("APLIKASI BUKU ALAMAT"));
            document.add(new Paragraph("Laporan Data Kontak"));
            document.add(new Paragraph("\n"));

            // 2. Buat Tabel PDF (6 Kolom)
            PdfPTable table = new PdfPTable(6); 
            table.setWidthPercentage(100); // Lebar tabel 100% dari halaman
            float[] columnWidths = {0.5f, 2f, 2f, 3f, 1.5f, 3f};
            table.setWidths(columnWidths);

            // Fungsi helper untuk Cell Header
            PdfPCell headerCell;
            String[] headers = {"ID", "NAMA", "TELEPON", "EMAIL", "PROPERTI", "KETERANGAN"};
            for (String header : headers) {
                headerCell = new PdfPCell(new Phrase(header));
                headerCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(headerCell);
            }

            // 3. Isi Data dari Database
            try (Statement stmt = koneksi.createStatement();
                 ResultSet rs = stmt.executeQuery(sql)) {

                while (rs.next()) {
                    // ID
                    PdfPCell idCell = new PdfPCell(new Phrase(String.valueOf(rs.getInt("id"))));
                    idCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(idCell);
                    
                    // Sisa kolom (Nama, Telepon, Email, Properti, Keterangan)
                    table.addCell(rs.getString("nama"));
                    table.addCell(rs.getString("telepon"));
                    table.addCell(rs.getString("email"));
                    table.addCell(rs.getString("properti"));
                    table.addCell(rs.getString("keterangan"));
                }
            }
            
            document.add(table);
            document.close();
            JOptionPane.showMessageDialog(this, "Ekspor PDF berhasil ke: " + fileToSave.getAbsolutePath());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ekspor data ke PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void importDataFromPDF(File fileToOpen) {
    int importedCount = 0;
    // Deklarasi PDDocument di luar blok try agar bisa diakses di blok finally
    PDDocument document = null; 
    
    // SQL Statement untuk memasukkan data baru
    String sql = "INSERT INTO kontak (nama, telepon, email, alamat, properti, keterangan) VALUES (?, ?, ?, ?, ?, ?)";
    
    try { 
        // --- KOREKSI UNTUK PDFBOX 2.x ---
        // Panggilan sederhana tanpa MemoryUsageSetting
        document = PDDocument.load(fileToOpen); 
        
        // 1. Ekstrak Semua Teks
        PDFTextStripper stripper = new PDFTextStripper();
        String text = stripper.getText(document);
        
        // 2. Analisis dan Parsing Teks
        String[] lines = text.split("\\n"); 
        
        try (java.sql.PreparedStatement pstmt = koneksi.prepareStatement(sql)) {
            
            for (String line : lines) {
                // Logika Parsing Teks (MENGASUMSIKAN format data terstruktur)
                // Peringatan: Logika parsing teks dari PDF sangat bergantung pada tata letak file sumber.
                
                // Contoh Parsing Sederhana (Menggunakan Koma sebagai pemisah di dalam baris)
                // Ini hanya ilustrasi. Anda mungkin perlu Regex atau pola yang lebih kompleks.
                String[] data = line.split(",", -1);
                
                // Asumsi data array [Nama, Telepon, Email, Alamat, Properti, Keterangan]
                if (data.length >= 6) { 
                    pstmt.setString(1, data[0].trim()); // Nama
                    pstmt.setString(2, data[1].trim()); // Telepon
                    pstmt.setString(3, data[2].trim()); // Email
                    pstmt.setString(4, data[3].trim()); // Alamat
                    pstmt.setString(5, data[4].trim()); // Properti
                    pstmt.setString(6, data[5].trim()); // Keterangan
                    pstmt.addBatch();
                    importedCount++;
                }
            }
            pstmt.executeBatch();
        }

        JOptionPane.showMessageDialog(this, "Impor " + importedCount + " data dari PDF selesai. Cek data.");
        loadData();

    } catch (IOException e) { 
        // Tangani masalah IO, termasuk kegagalan load() atau InvalidPasswordException
        JOptionPane.showMessageDialog(this, "Gagal membaca file PDF (IO/Sandi Error): " + e.getMessage(), "Error PDF", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        // Tangani masalah SQL
        JOptionPane.showMessageDialog(this, "Database Error saat impor PDF: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Blok ini memastikan dokumen PDF selalu ditutup
        if (document != null) {
            try {
                document.close();
            } catch (IOException closeEx) {
                // Abaikan error saat menutup dokumen
            }
        }
    }
}
    
    //Konfirmasi saat terdapat data yang belum di simpan/diupdate
    private void confirmExit() {
        if (isDataModified) {
            // Tampilkan dialog konfirmasi jika ada perubahan
            int choice = JOptionPane.showConfirmDialog(
                this, 
                "Ada data yang belum disimpan. Yakin ingin keluar?", 
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
            );

            if (choice == JOptionPane.YES_OPTION) {
                // Keluar jika pengguna memilih YES
                System.exit(0);
            }
            // Jika memilih NO, tetap di program
            
        } else {
            // Langsung keluar jika tidak ada perubahan
            System.exit(0);
        }
    }
    
    //validasi Email dan TELPON
    private boolean isValidEmail(String email) {
        // Regex: ".*@.*" artinya string harus mengandung (@) di antara karakter lain (.*)
        return email.contains("@");
        
        /*
        * Jika ingin validasi yang lebih ketat, gunakan:
        * return email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");
        */
    }
    private boolean isNumeric(String str) {
        // Regex: "^[0-9]+$" artinya string harus dimulai (^) dan diakhiri ($) 
        // dengan satu atau lebih (+) digit (0-9).
        return str.matches("^[0-9]+$");
    }
    
    private void setupWindowCloseConfirmation() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                confirmExit();
                // Override default close operation agar tidak langsung keluar
                // PENTING: Pastikan JDialog/JFrame Anda menggunakan DO_NOTHING_ON_CLOSE
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbProperti;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
